--liquibase formatted sql

--changeset user_service:1
CREATE TABLE user_service.users(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INT NOT NULL UNIQUE,
        name VARCHAR(50) NOT NULL,
        surname VARCHAR(50) NOT NULL,
        birth_date DATE NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        active VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--changeset user_service:2
CREATE TABLE user_service.payment_cards(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INT REFERENCES user_service.users(user_id) ON DELETE CASCADE NOT NULL,
        number VARCHAR(16) NOT NULL UNIQUE,
        holder VARCHAR(100) NOT NULL,
        expiration_date DATE NOT NULL,
        active VARCHAR(30) NOT NULL DEFAULT 'INACTIVE',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payment_cards_user_id ON user_service.payment_cards(user_id);