--liquibase formatted sql

--changeset nyatska:1
CREATE TABLE users(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        surname VARCHAR(50) NOT NULL,
        birth_date DATE NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--changeset nyatska:2
CREATE TABLE payment_cards(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        number BIGINT NOT NULL UNIQUE,
        holder VARCHAR(100) NOT NULL,
        expiration_date DATE NOT NULL,
        active BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payment_cards_user_id ON payment_cards(user_id);
CREATE INDEX idx_payment_cards_user_active ON payment_cards(user_id, active);